public void testTwo() throws Exception {
    Connection conn = newConnection();
    Statement statement;
    int updateCount;
    try {
        statement = conn.createStatement();
        statement.execute("create user testuser password 'test'");
        statement.execute("create table testtable(v varchar(20))");
        statement.execute("insert into testtable values ('tennis'), ('tent'), ('television'), ('radio')");
        ResultSet rs = statement.executeQuery("call \"org.hsqldb.test.TestStoredProcedure.funcTest2\"('test')");
        rs.next();
        boolean b = rs.getBoolean(1);
        rs.close();
        assertTrue("test result not correct", b);
        statement.execute("create function func2(varchar(20)) returns boolean " + "SPECIFIC F2 LANGUAGE JAVA DETERMINISTIC NO SQL CALLED ON NULL INPUT EXTERNAL NAME 'CLASSPATH:org.hsqldb.test.TestStoredProcedure.funcTest2'");
        rs = statement.executeQuery("call func2('test')");
        rs.next();
        b = rs.getBoolean(1);
        rs.close();
        assertTrue("test result not correct", b);
        rs = statement.executeQuery("select count(*) from testtable where func2(v)");
        rs.next();
        int count = rs.getInt(1);
        assertTrue("test result not correct", count == 3);
        statement.execute("grant execute on specific function public.f2 to testuser");
    } catch (Exception e) {
        assertTrue("unable to execute call to procedure", false);
    } finally {
        conn.close();
    }
}
